In [1]:
# Importing all the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sb
from sklearn import preprocessing 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('TITANIC.csv')

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
df = df.drop(['Ticket' , 'Name', 'Cabin','PassengerId'] ,axis = 1)

In [4]:
df = df.dropna(subset = ['Embarked'] , how = 'any')

In [5]:
median_age = df.loc[:,'Age'].median()
df['Age'].fillna(value = median_age, inplace = True)

In [6]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [6]:
df.isnull().sum().sum()

0

In [22]:
df.shape

(889, 8)

In [18]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   889.000000  889.000000  889.000000  889.000000  889.000000   
mean    446.000000    0.382452    2.311586   29.315152    0.524184   
std     256.998173    0.486260    0.834700   12.984932    1.103705   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     224.000000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.000000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  889.000000  889.000000  
mean     0.382452   32.096681  
std      0.806761   49.697504  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Sex          889 non-null    object 
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64  
 6   Parch        889 non-null    int64  
 7   Fare         889 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 69.5+ KB


In [6]:
a,b =df['Survived'].value_counts()
print("Percentage of survived : ",(b / (b+a)) * 100)
print("Percentage of died : ",(a / (b+a)) * 100)

Percentage of survived :  38.24521934758155
Percentage of died :  61.754780652418454


In [7]:
df['Sex'] = df['Sex'].replace(['male' , 'female'] , [0,1])

In [33]:
df['Sex']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 889, dtype: int64

In [34]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    0  22.0      1      0   7.2500        S
1         1       1    1  38.0      1      0  71.2833        C
2         1       3    1  26.0      0      0   7.9250        S
3         1       1    1  35.0      1      0  53.1000        S
4         0       3    0  35.0      0      0   8.0500        S

In [8]:
df = pd.get_dummies(df , columns = ['Pclass' , 'Embarked' , 'SibSp' , 'Parch'] ,drop_first =True)

In [10]:
df.head()

Survived  Sex   Age     Fare  Pclass_2  Pclass_3  Embarked_Q  Embarked_S  \
0         0    0  22.0   7.2500         0         1           0           1   
1         1    1  38.0  71.2833         0         0           0           0   
2         1    1  26.0   7.9250         0         1           0           1   
3         1    1  35.0  53.1000         0         0           0           1   
4         0    0  35.0   8.0500         0         1           0           1   

   SibSp_1  SibSp_2  SibSp_3  SibSp_4  SibSp_5  SibSp_8  Parch_1  Parch_2  \
0        1        0        0        0        0        0        0        0   
1        1        0        0        0        0        0        0        0   
2        0        0        0        0        0        0        0        0   
3        1        0        0        0        0        0        0        0   
4        0        0        0        0        0        0        0        0   

   Parch_3  Parch_4  Parch_5  Parch_6  
0        0        0        0        0  
1        0        0        0        0  
2        0        0        0        0  
3        0        0        0        0  
4        0        0        0        0

In [9]:
x = df['Age'].values.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_age = min_max_scaler.fit_transform(x)
df['Age'] = x_age

x = df['Fare'].values.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_age = min_max_scaler.fit_transform(x)
df['Fare'] = x_age


In [10]:
df.head()

Survived  Sex       Age      Fare  Pclass_2  Pclass_3  Embarked_Q  \
0         0    0  0.271174  0.014151         0         1           0   
1         1    1  0.472229  0.139136         0         0           0   
2         1    1  0.321438  0.015469         0         1           0   
3         1    1  0.434531  0.103644         0         0           0   
4         0    0  0.434531  0.015713         0         1           0   

   Embarked_S  SibSp_1  SibSp_2  SibSp_3  SibSp_4  SibSp_5  SibSp_8  Parch_1  \
0           1        1        0        0        0        0        0        0   
1           0        1        0        0        0        0        0        0   
2           1        0        0        0        0        0        0        0   
3           1        1        0        0        0        0        0        0   
4           1        0        0        0        0        0        0        0   

   Parch_2  Parch_3  Parch_4  Parch_5  Parch_6  
0        0        0        0        0        0  
1        0        0        0        0        0  
2        0        0        0        0        0  
3        0        0        0        0        0  
4        0        0        0        0        0

In [11]:
X = df
y = df.pop('Survived')

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

reg = LogisticRegression()
reg.fit(X_train , y_train)
y_train_predict = reg.predict(X_train)
y_test_predict = reg.predict(X_test)

print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict))
print("Recall : " , metrics.recall_score(y_test, y_test_predict))
print("Precision : ", metrics.precision_score(y_test, y_test_predict))

Accuracy Score : 0.797752808988764
Confusion metrics : 
 [[141  26]
 [ 28  72]]
Recall :  0.72
Precision :  0.7346938775510204


In [14]:
print(metrics.classification_report(y_test, y_test_predict))
# Number of features = 19

              precision    recall  f1-score   support

           0       0.83      0.84      0.84       167
           1       0.73      0.72      0.73       100

    accuracy                           0.80       267
   macro avg       0.78      0.78      0.78       267
weighted avg       0.80      0.80      0.80       267



# Feature Selection through PCA

In [15]:
from sklearn.decomposition import PCA
pca = PCA(random_state = 0)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=0,
    svd_solver='auto', tol=0.0, whiten=False)

In [21]:
np.cumsum(pca.explained_variance_ratio_)

array([0.25660978, 0.43762921, 0.56940685, 0.68949847, 0.76618616,
       0.82834467, 0.88656461, 0.91703124, 0.93891313, 0.9534888 ,
       0.9663011 , 0.97555871, 0.98089251, 0.98586594, 0.98979186,
       0.99311116, 0.99608142, 0.99890854, 1.        ])

In [16]:
pca_final = PCA(n_components = 10, random_state = 41)

X_train_pca = pca_final.fit_transform(X_train)
X_test_pca = pca_final.transform(X_test)

### Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression

reg_pca = LogisticRegression()

reg_pca.fit(X_train_pca, y_train)
y_test_predict_lr = reg_pca.predict(X_test_pca)

In [27]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_lr))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_lr))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_lr))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_lr))

Accuracy Score : 0.7940074906367042
Confusion metrics : 
 [[139  28]
 [ 27  73]]
Recall :  0.73
Precision :  0.7227722772277227


In [28]:
print(metrics.classification_report(y_test, y_test_predict_lr))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       167
           1       0.72      0.73      0.73       100

    accuracy                           0.79       267
   macro avg       0.78      0.78      0.78       267
weighted avg       0.79      0.79      0.79       267



### KNN 

In [30]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train_pca, y_train)
y_test_predict_knn = classifier.predict(X_test_pca)

In [31]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_knn))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_knn))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_knn))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_knn))

Accuracy Score : 0.7640449438202247
Confusion metrics : 
 [[138  29]
 [ 34  66]]
Recall :  0.66
Precision :  0.6947368421052632


In [32]:
print(metrics.classification_report(y_test, y_test_predict_knn))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       167
           1       0.69      0.66      0.68       100

    accuracy                           0.76       267
   macro avg       0.75      0.74      0.75       267
weighted avg       0.76      0.76      0.76       267



### SVM

In [33]:
from sklearn.svm import SVC
classifier_svc = SVC()
classifier_svc.fit(X_train_pca , y_train)
y_test_predict_svm = classifier_svc.predict(X_test_pca)

In [34]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_svm))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_svm))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_svm))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_svm))

Accuracy Score : 0.7940074906367042
Confusion metrics : 
 [[150  17]
 [ 38  62]]
Recall :  0.62
Precision :  0.7848101265822784


In [35]:
print(metrics.classification_report(y_test, y_test_predict_knn))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       167
           1       0.69      0.66      0.68       100

    accuracy                           0.76       267
   macro avg       0.75      0.74      0.75       267
weighted avg       0.76      0.76      0.76       267



### Decision Tree

In [40]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth = 50)
clf = clf.fit(X_train_pca , y_train)
y_test_predict_dt = clf.predict(X_test_pca)

In [41]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_dt))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_dt))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_dt))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_dt))

Accuracy Score : 0.6928838951310862
Confusion metrics : 
 [[122  45]
 [ 37  63]]
Recall :  0.63
Precision :  0.5833333333333334


In [42]:
print(metrics.classification_report(y_test, y_test_predict_dt))

              precision    recall  f1-score   support

           0       0.77      0.73      0.75       167
           1       0.58      0.63      0.61       100

    accuracy                           0.69       267
   macro avg       0.68      0.68      0.68       267
weighted avg       0.70      0.69      0.70       267



# Feature selection through RFE

In [18]:
df_train,df_test = train_test_split(df, train_size = 0.7, random_state = 42)

In [41]:
from sklearn.feature_selection import RFE

rfe = RFE(reg, 10)
rfe = rfe.fit(X_train, y_train)

In [42]:
temp_df = pd.DataFrame({'Columns' : X_train.columns, 'Included' : rfe.support_, 'Ranking' : rfe.ranking_})
temp_df

Columns  Included  Ranking
0          Sex      True        1
1          Age      True        1
2         Fare     False        3
3     Pclass_2      True        1
4     Pclass_3      True        1
5   Embarked_Q     False        7
6   Embarked_S     False        2
7      SibSp_1     False        8
8      SibSp_2     False        5
9      SibSp_3      True        1
10     SibSp_4      True        1
11     SibSp_5     False        6
12     SibSp_8      True        1
13     Parch_1      True        1
14     Parch_2     False        9
15     Parch_3     False       10
16     Parch_4      True        1
17     Parch_5      True        1
18     Parch_6     False        4

In [43]:
imp_col = X_train.columns[rfe.support_]
imp_col

Index(['Sex', 'Age', 'Pclass_2', 'Pclass_3', 'SibSp_3', 'SibSp_4', 'SibSp_8',
       'Parch_1', 'Parch_4', 'Parch_5'],
      dtype='object')

In [44]:
X_train_new = df_train[imp_col]
X_train_new.head()

Sex       Age  Pclass_2  Pclass_3  SibSp_3  SibSp_4  SibSp_8  Parch_1  \
486    1  0.434531         0         0        0        0        0        0   
293    1  0.296306         0         1        0        0        0        0   
173    0  0.258608         0         1        0        0        0        0   
450    0  0.447097         1         0        0        0        0        0   
361    0  0.359135         1         0        0        0        0        0   

     Parch_4  Parch_5  
486        0        0  
293        0        0  
173        0        0  
450        0        0  
361        0        0

In [45]:
regressor = LogisticRegression()
regressor.fit(X_train_new, y_train)
y_train_predict_new = regressor.predict(X_train_new)

X_test_new = df_test[imp_col]
y_test_predict_new = regressor.predict(X_test_new)

In [46]:
temp_df_new = pd.DataFrame({'Actual' : y_test , 'Predicted' : y_test_predict_new})
temp_df_new

Actual  Predicted
281       0          0
435       1          1
39        1          1
418       0          0
585       1          1
..      ...        ...
454       0          0
632       1          0
693       0          0
741       0          0
430       1          0

[267 rows x 2 columns]

In [47]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_new))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_new))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_new))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_new))

Accuracy Score : 0.8089887640449438
Confusion metrics : 
 [[145  22]
 [ 29  71]]
Recall :  0.71
Precision :  0.7634408602150538


In [48]:
print(metrics.classification_report(y_test, y_test_predict_new))
# Number of features = 10

              precision    recall  f1-score   support

           0       0.83      0.87      0.85       167
           1       0.76      0.71      0.74       100

    accuracy                           0.81       267
   macro avg       0.80      0.79      0.79       267
weighted avg       0.81      0.81      0.81       267



### After building various types of classification modles, based on thier accuracy we can say that after selecting 10 featured columns through RFE we get a accuracy score of about 80 %.
### This modle is the best modle we have.